---
abstract: 'Simple L<Lucy> Interface'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Lucy::Store::RAMFolder: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LucyX-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Data::Page: 0
  Exception::Simple: 0
  Lucy: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
